### ISSUE TITLE
How to install and use?

### ISSUE THREAD

**Issue by BaumGuard** [pgcudahy/mlrpt-runner#2]
Hi,

could you please provide some documentation about how to setup and use this program? That would be very helpful.

Thank you in advance!

**Comment by pgcudahy** [comment]
Thanks for checking it out, but I never got it working satisfactorily before my RTL-SDR stopped working. These are in jupyter notebooks using an R kernel (simple guide [here](https://richpauloo.github.io/2018-05-16-Installing-the-R-kernel-in-Jupyter-Lab/)) . You can walk through the notebooks in order of `Calibrate_receiver.ipynb`, then `Satellite_orbital_data.ipynb`, and then `Schedule_recordings.ipynb`.

**Comment by BaumGuard** [comment]
I am using a Raspberry Pi 4 with Raspbian for satellite reception. The instructions you sent me are only for Windows and OSX, but I will try to install Jupyter on my Pi. Actually, I don't have any experiences with Jupyter and I've heard of it for the first time when I discovered your program. But how should I proceed after entering my station's data?

**Comment by pgcudahy** [comment]
Like I said, it didn't really work, so I wouldn't bother if you don't
understand the R language.
